Analysis Fixture
virtool/virtool-workflow pull request #91
Opened 2020-12-22 19:47 UTC by BlakeASmith

Adds a new fixture `analysis`

Resolves #85

Depends on #90

2020-12-29 21:09 UTC, igboyes commented
Please resolve merge conflicts.

2020-12-29 21:21 UTC, BlakeASmith commented
> Please resolve merge conflicts.

Resolved.

2021-01-06 20:19 UTC, igboyes requested changes
I am worried a bit about the case where a workflow developer tries to upload two files with the same name. We may want an `id` field as well with an integer prepended to the name. This would also be the file's name in the application data location.

2021-01-06 20:19 UTC, igboyes commented on virtool_workflow/uploads/files.py
> +VirtoolFileFormat = Literal[
Please change to:
- `sam`
- `bam`
- `fasta`
- `fastq`
- `csv`
- `tsv`
- `json`

We should also have an "unknown" format.

2021-01-06 20:19 UTC, igboyes commented on virtool_workflow/db/db.py
> +    async def _generate_file_id(self, filename: str) -> str:
Drop this. Only used for user uploads.

2021-01-06 20:30 UTC, BlakeASmith commented on virtool_workflow/abc/db.py
> +        ...
No it can be removed.

2021-01-07 00:19 UTC, igboyes requested changes
One more change...

2021-01-07 21:51 UTC, igboyes approved these changes
Thanks for persevering!

2021-01-07 21:51 UTC, merged